apiVersion: v1
kind: Service
metadata: 
  name: flask-hello-service
spec:
  type: NodePort
  ports:
    - port: 5000   #application port
      targetPort: 5000 #target port
      nodePort: 30008
  selector:
    app: flask-hello
    